email_credentials = ["toaddr","fromaddr","fromaddrlogin"]
mysql_credentials = ['localhost', 'dbusername', 'dbpassword', 'dbname']
channel = "channelname"
YOUTUBE_DEVELOPER_KEY = "hkjashdjkHJKHJKDHJKHjkahdjkahk"
YOUTUBE_PLAYLIST = "PLNSDHjksahdjkajksak"
CURRENT_USER = ""
VARIABLE = ""
POKEMON = ""
CAUGHT = ""